<?php
include 'location.php';
$locations = [];
$location = new Location();
$location->id = 0;
$location->cords = "1041,327,842,226";
$location->name = "Science Museum";
$location->description = "Het motto van NEMO is Hands On! De objecten in NEMO zijn vaak experimentele opstellingen waarbij de bezoeker zelf een wetenschappelijk verschijnsel op het gebied van natuurkunde, scheikunde, biologie en gedragswetenschappen kan onderzoeken. Het museum wil jongeren door experimenten enthousiasmeren voor wetenschap en techniek. Zo'n 38% van de bezoekers is jonger dan 18 jaar.";
array_push($locations, $location);
$location = new Location();
$location->id = 1;
$location->cords = "414,293,566,440";
$location->name = "Dam Square";
$location->description = "De Dam is een plein in het centrum van Amsterdam. Het is het historische hart van de stad en de locatie van veel evenementen van nationale betekenis. Aan en op de Dam staan het Koninklijk Paleis, de Nieuwe Kerk en het Nationaal Monument, waar de jaarlijkse Nationale Dodenherdenking wordt gehouden.";
array_push($locations, $location);
$location = new Location();
$location->id = 2;
$location->cords = "320,775,687,966";
$location->name = "Rijksmuseum";
$location->description = "Het Rijksmuseum in Amsterdam is een van de zestien rijksmusea in Nederland. De collectie biedt een overzicht van de Nederlandse kunst en geschiedenis met onder andere werken van 17e-eeuwse Nederlandse meesters als Rembrandt, Vermeer en Hals. Het museum is sinds 1885 gevestigd in het Rijksmuseumgebouw dat ontworpen werd door de Nederlandse architect Pierre Cuypers.";
array_push($locations, $location);
$location = new Location();
$location->id = 3;
$location->cords = "133,271,320,474";
$location->name = "Red Light District";
$location->description = "De Wallen is het middeleeuwse stadscentrum dat wordt doorkruist door grachten en smalle steegjes vol met traditionele bars. De Oude Kerk, omringd door de met neonlampen verlichte rosse buurt, is een eeuwenoude voormalige kerk waarin culturele evenementen worden georganiseerd.";
array_push($locations, $location);
$location = new Location();
$location->id = 4;
$location->cords = "52,810,262,978";
$location->name = "Vondel Park";
$location->description = "Het Vondelpark is een langgerekt stadspark in Amsterdam, daterend uit 1865. Het park ligt in het stadsdeel Amsterdam-Zuid, op de grens met het stadsdeel Amsterdam-West en ten zuidwesten van de Amsterdamse grachtengordel. Het strekt zich uit van de Stadhouderskade tot aan de Amstelveenseweg.";
array_push($locations, $location);
$location = new Location();
$location->id = 5;
$location->cords = "885,680,1046,964";
$location->name = "Windmill";
$location->description = "De Gooyer is een stellingmolen aan de Amsterdamse Funenkade, bij de Zeeburgerstraat / hoek Sarphatistraat, tussen de Nieuwe Vaart en Singelgracht. De molen dankt zijn naam volgens sommige bronnen aan het feit dat de molen door zijn hoogte uitkijkt over Het Gooi, andere bronnen melden dat de naam afkomstig is van twee voormalige eigenaars die afkomstig waren uit het Gooiland.";
array_push($locations, $location);
